feat: 更新部分代码
vietnh1009/ASCII-generator pull request #55
Opened 2024-11-20 09:45 UTC by 767829413

2024-11-20 09:53 UTC, cdc12345 commented
please use english...

2024-11-20 10:16 UTC, HChaZZY commented
Please use English, as @cdc12345 has said.
Meanwhile, please consider removing your output file `data/output.txt` or add them to `.gitignore` to maintain a clean repo.

2024-11-20 10:16 UTC, HChaZZY commented
Please use English, as @cdc12345 has said.
Meanwhile, please consider removing your output file `data/output.txt` or add them to `.gitignore` to maintain a clean repo.

2024-11-20 10:32 UTC, Justjustifyjudge commented on data/output.txt
I think if you could add output.txt into .gitignore file would do better for the container to hold this repo, maybe?

2024-11-20 10:37 UTC, Justjustifyjudge commented on .flake8
why should these two rules be added? For a green hand, I don't understand.

2024-11-20 12:03 UTC, Saukiya commented
That's not the rule.
Please don't throw rubbish

2024-11-20 12:17 UTC, H-Sofie requested changes
This commit is meaningless, as it only modifies code formatting standards without making a significant contribution to readability.

2024-11-20 17:54 UTC, MRSlouzk commented
format some file and commit？hmmm...

2024-11-21 05:32 UTC, 767829413 commented
I'm running 

```bash
python3 -u img2txt.py --input /home/tmp/pexels-pixabay-163016.jpg --output /home/tmp/pexels-pixabay-163016.txt and I'm getting an error: code/python/ASCII- generator/img2txt.py:25: SyntaxWarning: invalid escape sequence ‘\|’
  CHAR_LIST = ‘$@B%8&WM#*oahkbdpqwmZO0QLCJUYXzcvunxrjft/\|()1{}[]? -_+~<>i!lI;:,\‘^`’. ’, 
```
my pythion version is 

```bash
python3 -V
Python 3.12.3
```
so in order to solve this problem, I modified the way to write CHAR_LIST, and used Flake8 as my Python code checker, sorry for initiating an inappropriate PR, the reason why I used the Chinese commit is because I didn't see the relevant contribution requirements, here I made the change

2024-11-21 05:51 UTC, H-Sofie commented
Plz refer to #52

2024-11-21 08:31 UTC, drsanwujiang commented on utils.py
These changes seem meaningless.

2024-11-21 08:34 UTC, closed without merging